In [2]:
def hello():
    print('Howdy!')
    print('Howdy!!!')
    print('Hello there.')

In [3]:
hello()

Howdy!
Howdy!!!
Hello there.


In [4]:
import random
def getAnswer(answerNumber):
    if answerNumber == 1:
           return 'It is certain'
    elif answerNumber == 2:
        return 'It is decidedly so'
    elif answerNumber == 3:
        return 'Yes'
    elif answerNumber == 4:
        return 'Reply hazy try again'
    elif answerNumber == 5:
        return 'Ask again later'
    elif answerNumber == 6:
        return 'Concentrate and ask again'
    elif answerNumber == 7:
        return 'My reply is no'
    elif answerNumber == 8:
        return 'Outlook not so good'
    elif answerNumber == 9:
           return 'Very doubtful'

In [5]:
r = random.randint(1, 9)
fortune = getAnswer(r)
print(fortune)

Reply hazy try again


In [11]:
return_value=

SyntaxError: invalid syntax (<ipython-input-11-0cc2ba9a9346>, line 1)

In [21]:
print('I do like this')
print('I do like this')

I do like this
I do like this


In [22]:
print('cat','dog')

('cat', 'dog')


In [25]:
def spam():
    eggs = 31337
spam()
print(eggs)

NameError: name 'eggs' is not defined

In [24]:
def spam():
    eggs = 99
    bacon()
    print(eggs)

def bacon():
    ham = 101
    eggs = 0

spam()

99


In [31]:
def spam():
    ok=1

def spam2():
    ok=2
    spam()
    print(ok)
spam2()

2


In [33]:
def spam():
    eggs = 'spam local'
    print(eggs) # prints 'spam local'
        
def bacon():
    eggs = 'bacon local'
    print(eggs) # prints 'bacon local'
    spam()
    print(eggs) # prints 'bacon local'

eggs = 'global'
bacon()
print(eggs) # prints 'global'

bacon local
spam local
bacon local
global


In [4]:
def spam():
    global eggs
    eggs='spam'

eggs='global'
spam()
print(eggs)

spam


In [5]:
def spam():
    print(eggs) # ERROR!
    eggs = 'spam local'

eggs = 'global'
spam()

UnboundLocalError: local variable 'eggs' referenced before assignment

In [9]:
def spam():
    print(eggs) # ERROR!
    global eggs
    eggs = 'spam local'

eggs = 'global'
spam()

global


<ipython-input-9-ed256fc99ed9>:3: SyntaxWarning: name 'eggs' is used prior to global declaration
  global eggs


In [10]:
def spam(divideBy):
    return 42 / divideBy

In [12]:
spam(1)

42

In [14]:
spam(0)

ZeroDivisionError: integer division or modulo by zero

In [21]:
def spam(divideBy):
    try:
        return 42/divideBy
    except ZeroDivisionError:
        print('Error: Invalid argument.')

In [22]:
spam(1)

42

In [24]:
spam(0)

Error: Invalid argument.


In [26]:
def spam(DivideBy):
    return 42 / DivideBy
try: 
    print(spam(2))
    print(spam(12))
    print(spam(0))
    print(spam(1))    
except ZeroDivisionError:
    print('Error: Invalid argument.')

21
3
Error: Invalid argument.


In [32]:
for i in range(1,10):
    i=i+1
    if i==6:                
        continue
    print(i)

2
3
4
5
7
8
9
10


In [40]:
import random
import numpy as np
secretNumber=np.random.randint(1,20,size=(2,4))
print(secretNumber)

[[18 15  7  1]
 [ 1  3  8 15]]


In [41]:
np.random.randint(1,20,size=(2,4))

array([[ 5, 18, 10, 10],
       [ 1, 19,  7, 14]])

In [43]:
import random
secretNumber=random.randint(1,20)
print('I am thinking of a number between 1 and 20.')

for guessesTaken in range(1,7):
    print('Take a guess.')
    guess=int(input())
    
    if guess < secretNumber:
        print('Your guess is too high.')
    elif guess > secretNumber:
        print('Your guess is too high.')
    else:
        break # This condition is the corret guess

if guess==secretNumber:
    print('Good job! You guessed my number in '+str(guessesTaken)+' guesses!')
else:
    print('Nope. The number I was thinking of was '+str(secrectNumber))

I am thinking of a number between 1 and 20.
Take a guess.
9
Your guess is too high.
Take a guess.
4
Your guess is too high.
Take a guess.
3
Your guess is too high.
Take a guess.
2
Good job! You guessed my number in 4 guesses!
